### ISSUE TITLE
student can send support request to teacher forum

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#12]
In the report problem input mask, the support forum where the issue should be posted needs to be selected. Sarah (student in Testschule 1) can select the forum for teachers of her school. When trying to select it, the following error is displayed:

```
Activity is hidden
Error code: requireloginerror
* line 3028 of /lib/moodlelib.php: require_login_exception thrown
* line 509 of /lib/externallib.php: call to require_login()
* line 160 of /local/edusupport/externallib.php: call to external_api::validate_context()
* line 255 of /lib/externallib.php: call to local_edusupport_external::create_issue()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
```
Add exception handling and hide forum from students

The schoolforum should be preselected and not the eduvidual forum.

**Comment by rschrenk** [comment]
solved in 2e5786fe7be10640af46c5491dceecb506e73a01
