### ISSUE TITLE
Course name of helpdesk mustn't be changed

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#13]
Managers should not have the possibility to edit the course name of the helpdesk course as this name is used for selecting the correct forum. If the manager removes the school name, users on more than one school wouldn't know where to post the issue.

**Comment by rschrenk** [comment]
The plugin prevents now the following capabilities:
`
        $capabilities = array(
            'moodle/course:activityvisibility',
            'moodle/course:changecategory',
            'moodle/course:changefullname',
            'moodle/course:changeidnumber',
            'moodle/course:changeshortname',
            'moodle/course:enrolconfig',
            'moodle/course:manageactivities',
            'moodle/course:delete',
            'moodle/course:reset',
            'moodle/course:visibility',
            'moodle/restore:configure',
            'moodle/restore:restorecourse',
            'moodle/restore:restoresection',
            'moodle/restore:viewautomatedfilearea',
        );
`
