### ISSUE TITLE
more than one forum for eduvidual support

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#14]
Susanne is manager in Testschule 1 and Teacher in Testschule 9. She has two possibilities to contact the eduvidual support:

- Helpdesk (eduvidual) > Helpdesk > #7
- Helpdesk (eduvidual) > Helpdesk > Susanne Lehrerin (7)

There should only be one option

**Comment by rschrenk** [comment]
This is not a bug, this is only for susanne, as I changed the name pattern for groups recently. Removed the "old" groups manually.
