### ISSUE TITLE
Forum selection is gone

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#16]
when reporting an issue the forum selection is now completely gone :(

**Comment by rschrenk** [comment]
solved in 7d579215263db7b27d736ecf416cc36384c77a37

**Comment by lassnj** [comment]
Bernhard (student Testschule 1) still has no forum selection. He hasn't posted anything so far.

**Comment by rschrenk** [comment]
Yes, he has exactly one target to post issues to. Hence there is no other option, the selection is not shown.
