### ISSUE TITLE
broken link in closed Issu

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#21]
The link to the discussion page of the closed issue [https://t1.eduvidual.org/local/edusupport/issue.php?discussion=26&replyto=0&delete=0&lang=en](https://t1.eduvidual.org/local/edusupport/issue.php?discussion=26&replyto=0&delete=0&lang=en) is broken:
[https://t1.eduvidual.org/local/edusupport/%7B$a-%3Etodiscussinurl%7D](https://t1.eduvidual.org/local/edusupport/%7B$a-%3Etodiscussinurl%7D)

**Comment by rschrenk** [comment]
fixed in f3aa9053ccb4b1ed65737586d7cbc021568a1722
