### ISSUE TITLE
cannot assign issue

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#22]
When JuliaL Admin tries to assign the issue [https://t1.eduvidual.org/local/edusupport/issue.php?d=27#](https://t1.eduvidual.org/local/edusupport/issue.php?d=27#) the Following error occurs:
`Error: -2`

**Comment by rschrenk** [comment]
Dear Julia,
Julia Admin is not part of the support team. If you want to try it out with that account, you have make her a support team member in Site Administration > Plugins > Local Plugins > eduSupport (in German its just called "Hilfe")
Robert
