### ISSUE TITLE
Missing Answer Button

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#25]
A 2nd Level Support-Member (JuliaL.) cannot answer a support-Request: no answer-Button is displayed:
[https://t1.eduvidual.org/local/edusupport/issue.php?d=28](https://t1.eduvidual.org/local/edusupport/issue.php?d=28)

Manager (Lisa) can answer although she pushed the request to 2nd level.

**Comment by rschrenk** [comment]
should be solved. please try again.
