### ISSUE TITLE
thirdparty libs

### ISSUE THREAD

**Issue by danmarsden** [center-for-learning-management/moodle-local_edusupport#3]
Hi there - saw this in the plugins review queue, and don't have time for a full review right now... but did notice some licencing issues which will be a blocker for approval.

I see some 3rd party code in js/screenshot.js (with no license or attribution.) and in amd/src/html2canvas.js (MIT)

you need to add details on these to a thirdpartylibs.xml file within your plugin.
https://docs.moodle.org/dev/Third_Party_Libraries

good luck finding the license/author for the screenshot.js file - I did a quick search and found it in a few places, but couldn't see one stating the original author or if they have assigned a license. If you can't find an author or license, you might not be able to include it in the code under GPL.

**Comment by rschrenk** [comment]
Hi, thank you for committing this issue and making me aware of it. At least for the MIT-licence it should not be problematic ("MIT licensed software can be re-licensed as GPL software, and integrated with other GPL software", https://en.wikipedia.org/wiki/MIT_License).

**Comment by danmarsden** [comment]
yeah - the mit one is simple, you just need to have it listed in the thirdpartylibs.xml file within your plugin. The other one looks like it could be challenging - unless you can find the original author and license they have associated with it.

**Comment by rschrenk** [comment]
Dear Dan, I checked the code and realized, that screenshot.js is not used at all. The plugin only requires html2canvas, which was published under the MIT licence. In commit d8eb736aa4002db5555b61368b7d56c21ca7ec26 I removed screenshot.js and included the thirdparty-lib description.
