### ISSUE TITLE
Manager 2nd level support

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#40]
Manager should be able to contact 2nd level support directly when reporting a problem. This option is gone now.

**Comment by rschrenk** [comment]
This option is not gone. It is only visible for those support courses, where the person creating the issue is enrolled as Trainer.

**Comment by lassnj** [comment]
It was also available in the report problem function. It is gone from there, so managers need to add the problem to their support course, thus reporting to themselves before being able to move it to the 2nd level support

**Comment by rschrenk** [comment]
as I already wrote, the option is not gone. But you need to select a support forum, where you are trainer of the course.
![edusupport](https://user-images.githubusercontent.com/8080807/101740211-d4068780-3ac8-11eb-9848-6d38551527a2.png)

**Comment by lassnj** [comment]
sorry, remembered it differently. We should rename the Checkbox to "Direkt dem 2nd Level Support zuweisen".
