### ISSUE TITLE
Gruppen in Kursen

### ISSUE THREAD

**Issue by dasistwas** [center-for-learning-management/moodle-local_edusupport#48]
Hallo @rschrenk ,

wir hatten folgenden Fall: Im Support-Kurs waren mehrere Leute eingeschrieben, die auf FAQ, und Announcements Zugriff hatten. Diese waren alle in einer Gruppe. Es hat dann einer aus der Gruppe ein Support-Ticket angelegt. Das ist dann an die ganze Gruppe gegangen (Die waren etwas erstaunt über die Anfragen und vielen Mails). 
Frage 1: Ist dieses Verhalten so gewollt? (Es gibt ein Dropdown wo man die Gruppe auswählen kann, aber da kennt sich niemand aus)
Frage 2: Wäre es OK, wenn wir automatisch alle Anfragen ausschließlich an die für den User erstellte Gruppe schicken und nicht an eine andere im Kurs vorhandene Gruppe?

**Comment by rschrenk** [comment]
Hallo,

die Regelung über Benachrichtigungen basiert ganz normal auf der Moodle-Logik für Abonnements und Gruppen. Wenn du Gruppen verwendest solltest du das Forum auf getrennte Gruppen einstellen. Die Empfehlung zu Abonnements wäre, dass man kein verpflichtendes oder automatisches Abonnement einstellt, sondern optional.

Ich würde hier nicht mit dem Plugin irgendwas umsetzen, was die Moodle-Logik ausser Kraft setzt. Denn eigentlich kann man mit der genau steuern, wie sich ein Support-Forum verhält.

LG

**Comment by dasistwas** [comment]
@rschrenk ja, die Einstellung ist ja genau so, es gibt aber trotzdem ein Problem, wenn ein User in mehreren Gruppen ist. Dann kann dieser aussuchen in welcher Gruppe der User postet. Ich habe aber in der einen Gruppe 500 Leute drinnen, die dann das Support Ticket eines Users bekommen. Das ist halt eine Katastrophe, denn die kennen sich nicht aus. Vielleicht telefonieren wir dazu, ich denke nicht, dass das so angekommen ist wie ich es gemeint habe.

**Comment by rschrenk** [comment]
Lieber David,
das Problem liegt aber nicht am edusupport-Plugin, sondern an der falschen Konfiguration des Forums. Offenbar ist das Forum so aufgesetzt, dass es sich als Helpdesk eben nicht eigent. Wenn die Einstellungen so vorgenommen werden, wie von mir empfohlen, hast du das Problem nicht.
LG

**Comment by dasistwas** [comment]
@rschrenk ja das Mailproblem habe ich dann nicht, aber die Leute sehen dann die Tickets der gesamten Gruppe, wenn sie in das Forum gehen. Das ist ein Privacy Problem. Die User wissen halt einfach nicht, welche Gruppe die richtige ist, die wollen nur ein Problem melden.

**Comment by rschrenk** [comment]
Ja, es ist dennoch ein Problem der Kursorganisation und nicht des Plugins.
