### ISSUE TITLE
In admin Issues is't post added by student

### ISSUE THREAD

**Issue by mariusz-mp** [center-for-learning-management/moodle-local_edusupport#51]
Hello, thanks for the module, great thing. I have a little question about configurations. Global forum, set operators. The student completing the modal form is added to the course (separated group), his application can be seen on the forum. However, you cannot see this report in the admin tab - Notifications (Issues). The tickets added by the admin and help work correctly / are displayed in the lists. I checked it on MOODLE 3.9.10 and 3.9.11 instances, the same result each time. Where could I go wrong in the configuration?
I Tesdted on php7.3.22 and 7.4.10 and lsphp74
Mariusz Pulkowski

**Comment by rschrenk** [comment]
Hello Mariusz,

There is nothing wrong with your configuration, it works as expected.

if you use a global forum, there is single point that offers you the overview on open issues - the forum itself. In that case your support team should be enrolled to that course with the trainer role. Therefore you don't need the admin tab for the global forum. Using the global forum offers you a flat support structure using only a first level support.

The purpose of the admin tab is to provide an overview, if you have de-centralized helpdesk courses. These offer you the possibility to have three support levels. The first level support must be enrolled in the respective help desk courses. Your staff from second and third level support does not need to be enrolled in these courses. If a ticket is sent to the second level, or from second level to third level, it appears in the admin tab. So, the 2nd and 3rd level staff can reply to the ticket without being enrolled to the support course itself.

Kind regards

Robert

**Comment by mariusz-mp** [comment]
He,
Thank you for your answer. 
It is clear to me. Doubts have arisen as there is no way to redirect to the second or third level in the global help forum. Information e-mails (information on moodle) come about a new application. As you wrote, everything is on the forum. So, as I understand the idea, after the information we have to decide who takes the topic without preselection from the first level (I am writing here about students' applications). Our tickets (helpdesk) appear automatically in Admin issue (I guess because of assigning a ticket to a person other than the author).

When it comes to handling MOODEL, I have a person who knows the platform poorly, her task is to redirect tasks between three people.
And on a forum where there is a complete set of reports, it is not possible to redirect to another person.
I only have a few courses but with a large number of learners, building a support forum for each course .... The second argument is the question of the lecturer, the subject is the subject and not the technical service. The description in your email and documentation suggests that all students must be enrolled in this course. So creating one help course (not global) would require adding all participants (from all courses).
I was thinking of linking using meta courses but that would be complicating something simple.
Is there a chance that in the near future, in the global forum, there will be an option to submit tickets to the Admin issue panel with the option of delegating a ticket to another person?
Maybe I am asking about something simple, but I think I missed something from the idea of the configuration (great forum ;-)).
Regards


dr inż.  Mariusz Pulkowski

Kierownik działu

Dział ds. e-Nauczania

 

Szkoła Główna Służby Pożarniczej

ul. J. Słowackiego 52/54

01-629 Warszawa, Polska

tel.+48 22 56 17 361
***@***.***
www.sgsp.edu.pl


----- Wiadomość oryginalna -----
Od: Robert Schrenk ***@***.***)
Data: 25-11-2021 07:30
Do: center-for-learning-management/moodle-local_edusupport ***@***.***)
UDW: mariusz-mp ***@***.***), Author ***@***.***)
Temat: Re: [center-for-learning-management/moodle-local_edusupport] In admin Issues is't post added by student (Issue #51)

Hello Mariusz,

There is nothing wrong with your configuration, it works as expected.

if you use a global forum, there is single point that offers you the overview on open issues - the forum itself. In that case your support team should be enrolled to that course with the trainer role. Therefore you don't need the admin tab for the global forum. Using the global forum offers you a flat support structure using only a first level support.

The purpose of the admin tab is to provide an overview, if you have de-centralized helpdesk courses. These offer you the possibility to have three support levels. The first level support must be enrolled in the respective help desk courses. Your staff from second and third level support does not need to be enrolled in these courses. If a ticket is sent to the second level, or from second level to third level, it appears in the admin tab. So, the 2nd and 3rd level staff can reply to the ticket without being enrolled to the support course itself.

Kind regards

Robert

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rschrenk** [comment]
Dear @mariusz-mp 

There are currently no plans to further develop the centralized support forum. It is some "legacy"-function. The idea of the support forums is that you have departments of some kind, where the students of a particular group or cohort are enrolled. This course should only be used as a support forum and it is recommended to separate them from the learning courses.

Kind regards

Robert
