### ISSUE TITLE
multiple forums in one course

### ISSUE THREAD

**Issue by shreo1992-beep** [center-for-learning-management/moodle-local_edusupport#53]
hi @rschrenk 

i have made two forums for one course when i choose one dedicated supporter to one of them it shows me that the value has changed on both forums on the web page but on the database when i check the table local_edusupport_issues i find that only one dedicated supporter value change as shown below

 id | categoryid | courseid | forumid | dedicatedsupporter | archiveid
----+------------+----------+---------+--------------------+-----------
 21 |          1 |        7 |      37 |                  9 |         0
 20 |          1 |        7 |      38 |                  2 |         0

how can i fix this issue

or each course should have only one forum

**Comment by shreo1992-beep** [comment]
@rschrenk hope to respond

**Comment by rschrenk** [comment]
@shreo1992-beep 

sorry that this bugfix took some time. I released a new version of local_edusupport, that fixes this issue.
