### ISSUE TITLE
Can not access "Settings" from "Site Administration / Plugins / Local plugins"

### ISSUE THREAD

**Issue by caiadogithub** [center-for-learning-management/moodle-local_edusupport#55]
After installing v2.2.1 I got this at "**Site Administration** / **Plugins** / **Local plugins**":

"...
Manage local plugins
**Help** 
**Learning Analytics** 
____General Settings
,,,"

There is no "**Settings**" link under "**Help**"?

Moodle 3.11.4+
Postgres 12
PHP 7.4
Ubuntu 20.04

**Comment by rschrenk** [comment]
Well, it should look like this
![edusupport](https://user-images.githubusercontent.com/8080807/150389214-956f6e82-4d9d-4a63-994e-223e781a3e99.png)

**Comment by caiadogithub** [comment]
I can not access this screen because there is no "Settings" link under
"Help".

[image: Firefox_Screenshot_2022-01-20T20-27-00.954Z.png]


Em qui., 20 de jan. de 2022 às 14:20, Robert Schrenk <
***@***.***> escreveu:

**Comment by rschrenk** [comment]
The word "help" should be the link....

**Comment by caiadogithub** [comment]
I´m afraid it is not.

Take a look at the HTML code:

"...

<li><strong>Help</strong></li>
               <li>
        <ul class="list-unstyled ml-2">
                                            <li><a
href="https://www.mooc.nce.ufrj.br/admin/settings.php?section=local_edusupport_settings"></a></li>
                                                           </ul>
                                                 </li>

..."



Em qui., 20 de jan. de 2022 às 18:40, Robert Schrenk <
***@***.***> escreveu:

**Comment by rschrenk** [comment]
Which theme are you using?

Can you open the settings, when you navigate manually to _wwwroot_/admin/category.php?category=local_edusupport ?

**Comment by caiadogithub** [comment]
Tested on Boost and Fordson.



Em qui., 20 de jan. de 2022 às 19:56, Robert Schrenk <
***@***.***> escreveu:

**Comment by rschrenk** [comment]
> Can you open the settings, when you navigate manually to _wwwroot_/admin/category.php?category=local_edusupport ?

**Comment by caiadogithub** [comment]
Yes, I do.

I sent you a print screen on the email

Em sex., 21 de jan. de 2022 às 03:18, Robert Schrenk <
***@***.***> escreveu:

**Comment by rschrenk** [comment]
Ok, i pushed an update for the settings.php. Can you please replace it and see if that fixes the problem?

**Comment by caiadogithub** [comment]
Is Moodle repository updated too?

Em dom., 23 de jan. de 2022 às 06:55, Robert Schrenk <
***@***.***> escreveu:

**Comment by rschrenk** [comment]
No, I will do that once you confirmed it solves the problem. Please use the version from the GitHub repository.

You can either download it as ZIP and install through site administration or just replace the settings.php.

**Comment by caiadogithub** [comment]
Plugin updated!

It works!

Thanks!



Em dom., 23 de jan. de 2022 às 10:02, Robert Schrenk <
***@***.***> escreveu:

**Comment by rschrenk** [comment]
Great, new release is published!
