### ISSUE TITLE
Reporting some malfunctions

### ISSUE THREAD

**Issue by recchiad** [center-for-learning-management/moodle-local_edusupport#56]
Hello and thank you, really,  for this important plugin.
Unfortunately I can't configure it correctly, or there is some problem, because despite having entered the priorities and configured the first, second and third level users, on any boost theme that I am going to use (Boost, Fordson, Moove, Trema) the screenshot of image 4 (request for help in eduvidual T1) is different from mine (missing the "visible to" function, the wording of the call to the second level and the following flag.
Furthermore:
- it is not possible to display the functions referred to in images 6 (issue page) and 7 (page with the "assign" or "close" buttons)
- when I try to set up a dedicated user from the "supporter" function in the plugin / local plugins / Help section, the error "Cannot set up a dedicated supporter" appears
Where am I wrong?
I am using Moodle version 3.11.4

![param_conf](https://user-images.githubusercontent.com/98238078/150656884-79b3d204-22d5-4e2f-b5e6-a5589de873f0.jpg)
![image-requesthelp](https://user-images.githubusercontent.com/98238078/150656891-4a2566bd-5292-4ea2-9cc8-f021481eefe9.jpg)
![configuration_supporters](https://user-images.githubusercontent.com/98238078/150656897-e5f38d09-d2a3-4c61-9077-afb445319111.jpg)
![choose forum dedicated personnel](https://user-images.githubusercontent.com/98238078/150656902-8fe0a4ed-7ae6-4d4d-9b72-ae77b73e66d4.png)

**Comment by recchiad** [comment]
Sorry .. version of plugin Help in use is: 2.2.2 (2022011800)

**Comment by rschrenk** [comment]
Hello,
recently we found an incompatibility with PostreSQL. Are you using PostreSQL or MySQL/MariaDB?
Best regards

**Comment by recchiad** [comment]
Hi Robert,
our Moodle system adopts Mysql Server version: 8.0.27-0ubuntu0.20.04.1 (Ubuntu).

Best Regards

Domenico

**Comment by rschrenk** [comment]
Hello,

the "bugfix" in regard of PostreSQL caused another bug, that was solved in #59 
I think this was also the cause that you could not see the buttons "assign" and "close". Can you please update to version 2.2.4. It is already available at moodle.org

Kind regards
