### ISSUE TITLE
User ID does not exist or is deleted!

### ISSUE THREAD

**Issue by caiadogithub** [center-for-learning-management/moodle-local_edusupport#57]
When saving new supporters I got this error message: 

![Firefox_Screenshot_2022-01-23T15-51-39 887Z](https://user-images.githubusercontent.com/23316275/150686876-560b4738-f17c-439a-85fe-51a2170667cd.png)

There is no user with **Id=4** in the system. It was deleted.

Why not pick up only the active (non deleted) users?

Or even better: use a drop-down menu with the their names, instead of their IDs?

I need database access to find out the IDs.

**Comment by rschrenk** [comment]
Hello,

you do not need database access to find the ID. Just navigate to the profile of the respective user and note the ID-Parameter in the URL. Yes, a searchable list would indeed be better, but it would require additional time for development, that was not available.

Best regards
