### ISSUE TITLE
Title link - User XP

### ISSUE THREAD

**Issue by caiadogithub** [center-for-learning-management/moodle-local_edusupport#58]
"Supporters" tiltle link found on "_/local/edusupport/choosesupporters.php_" should send user back to "_/admin/settings.php?section=local_edusupport_settings_"

![Firefox_Screenshot_2022-01-23T16-01-10 832Z](https://user-images.githubusercontent.com/23316275/150687100-e2e0cdcc-a4e1-4cdd-93dc-eee614032e85.png)

**Comment by rschrenk** [comment]
sorry, what do you mean exactly? I cannot see something wrong there.

**Comment by caiadogithub** [comment]
The only clickable text on the page "_/local/edusupport/choosesupporters.php_" sends the user to site home page instead of sending him back to "_/admin/settings.php?section=local_edusupport_settings_"

**Comment by rschrenk** [comment]
You should see a form there, where you must enter the users of the user account that acts as a support staff.

is there no form?

please enable debugging on your site to see if there is an error.

**Comment by caiadogithub** [comment]
Yes, there is a form.

![Firefox_Screenshot_2022-01-27T13-55-12 946Z](https://user-images.githubusercontent.com/23316275/151372929-6830f7d9-91ab-44ca-be04-e50f213d5192.png)


The point is: from that page I can not go back directly to the Settings page. The title link send me to "/my/".

Ricardo

**Comment by rschrenk** [comment]
Ok, now I understand. It is fixed and new version is released.

**Comment by rschrenk** [comment]
Ok, now I understand. It is fixed and new version is released.

**Comment by caiadogithub** [comment]
Moodle repository is outdated.

Released: Tuesday, 25 January 2022, 6:10 AM

**Comment by rschrenk** [comment]
Interesting, it lists 2.2.4 as most recent version and 2.2.5 in "previous versions". Look here: https://moodle.org/plugins/local_edusupport/2.2.5/25900
