### ISSUE TITLE
Dedicated supporter could not be set 

### ISSUE THREAD

**Issue by caiadogithub** [center-for-learning-management/moodle-local_edusupport#59]
Can not set dedicated supporter.

Debug mode on: no error messages

![Firefox_Screenshot_2022-01-23T16-17-30 719Z](https://user-images.githubusercontent.com/23316275/150687737-b306895f-6d6e-4af0-9446-a031c3ab4364.png)

**Comment by rschrenk** [comment]
Oh yes, I made a very dumb error! Switched LIMIT and OFFSET values in an SQL-Query...

Please update to version 2.2.4, that I published also on moodle.org
