### ISSUE TITLE
From 2.Level to 3.Level

### ISSUE THREAD

**Issue by JochenBN** [center-for-learning-management/moodle-local_edusupport#60]
Hi Robert
Thanks for the plugin.

We have tried it in moodle 3.9.12 and have the following problem.

We have 3 user :
1. Trainer01 - with role teacher in Supportcourse. => 1.level
2. Trainer02  - he is defined in support team without no entry in Supportlevel => 2.Level
3.  Thirdlevel - defined in support team WITH an entry in field supportlevel => 3. Level

If normal User create an ticket, trainer01 can read and forward the ticket to 2.Level by clicking the button top right
Trainer01 can get back the ticket.
Trainer02 can read the ticket but there is NO button foward the ticket to 3.Level.

In Forum under rights i can see that the person with 2.Level und 3.Level have the role "eduSupport Team".
In Role management i can see that the right to foward to next level is unchecked.

Is the a bug or did i something wrong?

Regards
Jochen

**Comment by rschrenk** [comment]
Hello,

forwarding to the 3rd level is not done in the forum itself. This is achieved through the ticket management at /local/edusupport/issues.php

Kind regards
