### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by caiadogithub** [center-for-learning-management/moodle-local_edusupport#61]
**local_edusupport_moodle311_2022012500.zip**

**$plugin->version  = 2022012500;**
$plugin->requires = 2014051200;
$plugin->component = 'local_edusupport';
**$plugin->release = '2.2.4';**
$plugin->maturity = MATURITY_STABLE;

===============================

**local_edusupport_moodle311_2022012400.zip**

**$plugin->version  = 2022012400;**
$plugin->requires = 2014051200;
$plugin->component = 'local_edusupport';
**$plugin->release = '2.2.5';**
$plugin->maturity = MATURITY_STABLE;

**Comment by rschrenk** [comment]
yes, there was a typo in the build number.
