### ISSUE TITLE
Broken link when accessing forum discussion

### ISSUE THREAD

**Issue by caiadogithub** [center-for-learning-management/moodle-local_edusupport#62]
Hi,

Using PostgreSQL 12.

When I click on any discussion topic link I got this error message:

![Firefox_Screenshot_2022-01-27T22-30-29 342Z](https://user-images.githubusercontent.com/23316275/151454386-ba881ec1-b5a8-4c2b-90f6-c7d1127ac868.png)

**Comment by rschrenk** [comment]
changed the sql queries to be compatible with PostgreSQL in version 2.2.7
