### ISSUE TITLE
eduSupport: Helpdesk Course

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#8]
Users are not automatically assigned a group in the Helpdesk Course. Users are thus not allowed to add new topics or do anything in the course. All users need automatically be added to the Group for all users and teachers need to be added to the teachers-group as well.

The eduvidual Manager needs access to the group management so that he/she sees who is in which group.

Tested with Susanne's Account (same situation although manager in Testschule1 and teacher in Testschule 9)

**Comment by rschrenk** [comment]
this is intended behavior. We agreed not to create groups per user.

**Comment by lassnj** [comment]
Removed the Group Setting from Course Settings
